title: "Probabilistic ML Reading Group"
description: "Exploring *Probabilistic Machine Learning: Advanced Topics* together."
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Navigation structure
nav_order: 1
